Update patch set 6
Patch Set 6:

> Oops one of the tests failed:
 > StdPAPPolicyTest.testConstructorStringStringStringStringStringMapStringStringStringStringBooleanStringStringStringStringString:606
 > expected:<body> but was:<null>
Build back to normal now... 
this review is getting too bigger and plenty of files, checkstyle always makes it very difficult to focus on changes., 
StdPapPolicy needs more refactoring, about 18 more constructors, using +7 attributes flagged by Sonar. 
Please let me know if this is important to refactor., as there could be many changes in files. 
If could be merged, then i hope i can start fresh with other constructors., else will continue updating this.,

Patch-set: 6
Reviewer: Gerrit User 2543 <2543@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0