Update patch set 1
Patch Set 1:

Apologies!!!

Another twist on this story, I just now realise I had the incorrect test class referenced in the check in message. The class that causes that dependency is actually:

org.onap.policy.pdp.rest.api.test.NotificationAPITest

Test case that fails is the last one in that class:
threadTest()

The exception is:
Exception in thread "Thread-21" java.lang.NoClassDefFoundError: com/att/aft/dme2/api/DME2Exception
	at com.att.nsa.mr.client.impl.MRSimplerBatchPublisher$Builder.build(MRSimplerBatchPublisher.java:105)
	at org.onap.policy.utils.BusPublisher$DmaapPublisherWrapper.<init>(BusPublisher.java:75)
	at org.onap.policy.pdp.rest.notifications.NotificationServer.sendNotification(NotificationServer.java:193)
	at org.onap.policy.pdp.rest.notifications.NotificationController.sendNotification(NotificationController.java:202)
	at org.onap.policy.pdp.rest.XACMLPdpLoader$1.run(XACMLPdpLoader.java:204)
Caused by: java.lang.ClassNotFoundException: com.att.aft.dme2.api.DME2Exception
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
Exception in thread "Thread-23" java.lang.NoClassDefFoundError: com/att/aft/dme2/api/DME2Exception
	at com.att.nsa.mr.client.impl.MRSimplerBatchPublisher$Builder.build(MRSimplerBatchPublisher.java:105)
	at org.onap.policy.utils.BusPublisher$DmaapPublisherWrapper.<init>(BusPublisher.java:75)
	at org.onap.policy.pdp.rest.notifications.NotificationServer.sendNotification(NotificationServer.java:193)
	at org.onap.policy.pdp.rest.notifications.NotificationController.sendNotification(NotificationController.java:202)
	at org.onap.policy.pdp.rest.XACMLPdpLoader$1.run(XACMLPdpLoader.java:204)
Caused by: java.lang.ClassNotFoundException: com.att.aft.dme2.api.DME2Exception
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
[DEV: 2018-Mar-16 16:52:01,644][INFO ][main      ]

Does that shed any more light?

Patch-set: 1
Reviewer: Gerrit User 2787 <2787@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0